name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'
        
      - name: Install Databricks CLI
        run: |
          #/home/runner/.local/bin/databricks configure
          pip install databricks-cli
          pip install --upgrade urllib3 chardet
        
      - name: Import Notebooks to Databricks Workspace
        env:
          DATABRICKS_HOST: https://4207850410470993.3.gcp.databricks.com
          DATABRICKS_TOKEN: ${{ dapi4a0e47ceb2e1fe223f71ce2699e13c7c }}
        run: |
          databricks configure --token $DATABRICKS_TOKEN
          #export DATABRICKS_HOST=https://4207850410470993.3.gcp.databricks.com
          databricks workspace import_dir /home/runner/work/ZenniDEV/ZenniDEV /Shared/GCPCICD
