name: CI/CD for Databricks Notebooks

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy Notebooks to Databricks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use your preferred Python version

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ https://4207850410470993.3.gcp.databricks.com/ }}
        DATABRICKS_TOKEN: ${{ dapiafdcdc98c214854ab7c93a01a19d9d6a }}
      run: |
        databricks configure --token
        databricks workspace configure --host "${DATABRICKS_HOST}" --token "${DATABRICKS_TOKEN}"

    - name: Deploy Notebooks
      run: |
        databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD  # Update path and workspace-path as needed
