name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          databricks --version
          export PATH="$PATH:~/.local/bin"
          source ~/.bashrc  # or source ~/.zshrc for Zsh users
          #sudo curl -o /tmp/databricks.deb -L https://databricks.com/api/2.0/tools/install-cli
          #sudo rm -i /tmp/databricks.deb

      - name: Deploy notebooks
        run: |
          databricks workspace import_dir ganeshmurthyit/ZenniDEV/cleanup.py /Workspace/Shared/GCPCICD
