name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          su -
          curl -o /tmp/databricks.deb -L https://databricks.com/api/2.0/tools/install-cli
          dpkg -i /tmp/databricks.deb

      - name: Deploy notebooks
        run: |
          databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD
