name: Deploy to Databricks

on:
  push:
    branches:
      - QA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Import notebooks into Databricks workspace
      uses: databrickslabs/gha-databricks@v1.0.0
      with:
        databricks_host: ${{ secrets.DATABRICKS_HOST }}
        databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
        source_path: /home/runner/work/ZenniDEV
        destination_path: /Shared/DETeam/
        exclude: .github/workflows  # Exclude .github/workflows folder
