name: CI/CD Pipeline for QA Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install --upgrade databricks-cli
          pip install databricks-sdk
      - name: Set up Databricks CLI
        run: |
         echo "host = https://4207850410470993.3.gcp.databricks.com"> ~/.databrickscfg
      - name: Configure Databricks CLI
        run: |
          databricks configure    

      - name: Deploy to QA Databricks Workspace
        run: |
          databricks configure --token
          databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD
