name: Deploy to Databricks

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Authenticate with Databricks
      run: databricks configure --token && databricks workspace configure --token
      env:
        DATABRICKS_HOST: ${{ secrets.https://4207850410470993.3.gcp.databricks.com }}
        DATABRICKS_TOKEN: ${{ secrets.dapi3e127f2d288fbeae0f26bc537ae79433 }}

    - name: Import to Databricks Workspace
      run: databricks workspace import_dir https://github.com/ganeshmurthyit/ZenniDEV/tree/main/CICDTest /Workspace/Shared/GCPCICD
