name: CI/CD Pipeline for QA Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install databricks-cli

      - name: Deploy to QA Databricks Workspace
        run: |
          #databricks configure --token
          databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD
