name: CI/CD Pipeline for QA Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install --upgrade databricks-cli
      - name: Set up Databricks CLI
        run: |
          echo ${{ dapi0c11996cb775631820d17c1d3605c7d2 }} | databricks configure --token
          echo "host = https://4207850410470993.3.gcp.databricks.com" > ~/.databrickscfg

      - name: Configure Databricks CLI
        run: |
          databricks configure --profile ~/.databrickscfg    

      - name: Deploy to QA Databricks Workspace
        run: |
          #databricks configure --token
          databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD
