name: Databricks Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Deploy Notebooks
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ --key-file=ZenniDEV/databricks-362300-4eecbc223d73.json }}
        DATABRICKS_HOST: <https://4207850410470993.3.gcp.databricks.com>
        DATABRICKS_TOKEN: <dapi0c11996cb775631820d17c1d3605c7d2>
        DATABRICKS_CLUSTER_ID: <0215-061921-zf7bgs6c>
      run: |
        databricks configure --token
        databricks workspace import_dir ganeshmurthyit/ZenniDEV/ /Workspace/Shared/GCPCICD
